# Generated by Django 6.0.3 on 2026-05-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userrole_auditlog'),
        ('core', '0002b_userrole_safe'),
    ]

    operations = [
    ]
