# Generated by Django 6.0.3 on 2026-05-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_userrole_auditlog_0002b_userrole_safe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__username'], 'verbose_name': 'Association Utilisateur-Rôle', 'verbose_name_plural': 'Associations Utilisateur-Rôle'},
        ),
    ]
