# Generated by Django 6.0.4 on 2026-06-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_audit_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__email'], 'verbose_name': 'Association Utilisateur-Rôle', 'verbose_name_plural': 'Associations Utilisateur-Rôle'},
        ),
    ]
