# Generated by Django 6.0.5 on 2026-05-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_fieldmapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["level", "code"],
                "verbose_name": "Rôle PostgreSQL",
                "verbose_name_plural": "Rôles PostgreSQL",
            },
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "ordering": ["user__email"],
                "verbose_name": "Association Utilisateur-Rôle",
                "verbose_name_plural": "Associations Utilisateur-Rôle",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Niveau du rôle"),
        ),
        migrations.AlterField(
            model_name="fieldmapping",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fieldmapping",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="fieldmapping",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="fieldmapping",
            name="field_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="fieldmapping",
            name="model_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="fieldmapping",
            name="source_field_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="fieldmapping",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="Code du rôle"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Description du rôle"),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_roles",
                to="core.role",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postgres_role",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
