"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-3=#-gb(y!sq*&=2chy@7k#+0&-uv2#w%+v4!anm#u(=&g@797^'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get(
        'ALLOWED_HOSTS',
        'localhost,127.0.0.1,192.168.0.173,192.168.1.50, teraka-api.herokuapp.com,teraka-api.onrender.com'
    ).split(',') if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.gis',
    'core',
]

JAZZMIN_SETTINGS = {
    "site_title": "Teraka Admin",
    "site_header": "Teraka",
    "site_brand": "Teraka",
    "site_logo": "core/img/logo_teraka.png",
    "login_logo": "core/img/logo_teraka.png",
    "welcome_sign": "Bienvenue sur l'administration Teraka",
    "copyright": "Teraka Ltd",
    "search_model": ["core.Users"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Accueil", "url": "/"},
        {"name": "Déconnexion", "url": "/logout/"},
        {"name": "Support", "url": "https://www.teraka.org/", "new_window": True},
        {"model": "core.Users"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "core/css/custom_admin.css",
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible_list", "auth.group": "vertical_tabs"},
    "default_theme_mode": "auto",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'SIGNING_KEY': SECRET_KEY,
    'ALGORITHM': 'HS256',
    'USER_ID_FIELD': 'uuid_user',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_OBTAIN_SERIALIZER': 'core.serializers.PostgrestTokenSerializer',
    # Token lifetime settings (extend as needed)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Indispensable pour l'API
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware', # Compression des flux
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.AuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = 'core.Users'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
DB_ENGINE = os.environ.get('DB_ENGINE', 'django.contrib.gis.db.backends.postgis')
DB_NAME = os.environ.get('DB_NAME', 'teraka')
DB_USER = os.environ.get('DB_USER', 'postgres')
DB_PASSWORD = os.environ.get('DB_PASSWORD', 'ad,in')
DB_HOST = os.environ.get('DB_HOST', 'localhost')
DB_PORT = os.environ.get('DB_PORT', '5432')

# Server Port Configuration
DJANGO_PORT = int(os.environ.get('DJANGO_PORT', '8050'))
POSTGREST_PORT = int(os.environ.get('POSTGREST_PORT', '3050'))
ADMINER_PORT = int(os.environ.get('ADMINER_PORT', '8080'))
POSTGRES_PORT = int(os.environ.get('POSTGRES_PORT', DB_PORT))

if DATABASE_URL:
    from urllib.parse import urlparse
    parsed = urlparse(DATABASE_URL)
    DB_ENGINE = os.environ.get('DB_ENGINE', 'django.contrib.gis.db.backends.postgis')
    DB_NAME = parsed.path.lstrip('/') or DB_NAME
    DB_USER = parsed.username or DB_USER
    DB_PASSWORD = parsed.password or DB_PASSWORD
    DB_HOST = parsed.hostname or DB_HOST
    DB_PORT = str(parsed.port or DB_PORT)
    POSTGRES_PORT = int(DB_PORT)

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOW_ALL_ORIGINS = True # À restreindre en production
CORS_ALLOWED_ORIGINS = [
    f"http://localhost:{DJANGO_PORT}",
    f"http://0.0.0.0:{DJANGO_PORT}",
    f"http://127.0.0.1:{DJANGO_PORT}",
    f"http://localhost:{POSTGREST_PORT}",
    f"http://0.0.0.0:{POSTGREST_PORT}",
    f"http://127.0.0.1:{POSTGREST_PORT}",
    # Legacy hardcoded ports for backward compatibility
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_CREDENTIALS = True

LOGIN_REDIRECT_URL = '/accounts/profile/'
LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "core/static", # Or os.path.join(BASE_DIR, 'static') depending on your Django version
]
STATIC_ROOT = BASE_DIR / 'core/staticfiles'

import os
if os.name == 'nt': # Si vous êtes sur Windows
    # On récupère le chemin de l'environnement Conda actuel
    VENV_PATH = os.environ.get('CONDA_PREFIX')
    if VENV_PATH:
        os.environ['PATH'] = os.path.join(VENV_PATH, 'Library', 'bin') + os.pathsep + os.environ['PATH']
        GDAL_LIBRARY_PATH = os.path.join(VENV_PATH, 'Library', 'bin', 'gdal.dll')
        GEOS_LIBRARY_PATH = os.path.join(VENV_PATH, 'Library', 'bin', 'geos_c.dll')

POSTGREST_UPSTREAM = os.environ.get('POSTGREST_UPSTREAM', 'http://127.0.0.1:3000')

# ============================================================================
# PORT CONFIGURATION SUMMARY
# ============================================================================
# Configure ports via environment variables or defaults below:
#
# Environment Variables:
#   DJANGO_PORT=8000         — Django development/Gunicorn server
#   POSTGREST_PORT=3000      — PostgREST API server
#   ADMINER_PORT=8080        — Adminer database UI (optional)
#   POSTGRES_PORT=5432       — PostgreSQL database
#   DB_PORT=5432             — Alias for POSTGRES_PORT
#
# Usage in code:
#   from django.conf import settings
#   print(settings.DJANGO_PORT)
#   print(settings.POSTGREST_PORT)
#   print(settings.POSTGRES_PORT)
#
# Docker Compose:
#   export DJANGO_PORT=8000 POSTGREST_PORT=3000
#   docker compose up
#
# ============================================================================
PORT_CONFIG = {
    'django': DJANGO_PORT,
    'postgrest': POSTGREST_PORT,
    'adminer': ADMINER_PORT,
    'postgres': POSTGRES_PORT,
}